import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "./Components/Navbar";

const roboto = Roboto({
  subsets: ["latin"],
  variable:"--font-roboto",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable:"--font-work-sans",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     
        className={`${roboto.variable} ${workSans.variable}`}
      >
      
         <Navbar/>
        {children}
      </body>
    </html>
  );
}
